# Range in blocks. -1 means unlimited range.
announcement-range:
  join: 256
  quit: 256
  death: 256
  advancement: 256
  chat: -1

player-death-sound:
  enabled: false
  sound: "entity.wither.spawn"
  volume: 1.0
